[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[directory]
read_only = " ro"

[git_branch]
symbol = "git "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[package]
disabled = true

[c]
disabled = true

[nodejs]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[java]
disabled = true

[rust]
disabled = true

[perl]
disabled = true

[dotnet]
disabled = true

[swift]
disabled = true

[julia]
disabled = true

[haskell]
disabled = true

[zig]
disabled = true

[lua]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[elixir]
disabled = true

[ocaml]
disabled = true

[scala]
disabled = true

[vlang]
disabled = true

[crystal]
disabled = true

[python]
disabled = true

[nim]
disabled = true

