# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# change prefix to ctrl-a
set-option -g prefix C-a
bind C-a send-prefix # Pass on ctrl-a for other apps

set -sg escape-time 1 # quicker responses

bind r source-file ~/.tmux.conf \; display "Reloaded!" # Reload with prefix + r

bind M-l split-window -h -c "#{pane_current_path}" # Split panes horizontal
bind M-j split-window -v -c "#{pane_current_path}" # Split panes vertically

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind J resize-pane -D 2
bind K resize-pane -U 2
bind L resize-pane -R 2
bind H resize-pane -L 2

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g mouse on

set -g default-terminal "xterm-256color"

set-option -sa terminal-overrides ',alacritty:RGB'
set-option -g focus-events on

unbind -T prefix h
unbind -T prefix l

bind -T prefix l next-window
bind -T prefix h previous-window

unbind -T prefix p

#set-window-option -g mode-keys vi bind-key -t vi-copy ‘v’ begin-selection bind-key -t vi-copy ‘y’ copy-selection
set-window-option -g mode-keys vi

# Bind 'Escape' to exit copy-mode
bind -T copy-mode-vi Escape send-keys -X cancel

# Bind 'i' in copy mode to exit copy mode and pass input through (like Vim insert mode)
bind -T copy-mode-vi i send-keys -X cancel

# Make sure y copies to buffer
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

# Make sure p pastes the last buffer
bind p paste-buffer

# Make sure j/k scroll in copy mode (this is already default for vi mode)
# Same with h/l

# Make sure Ctrl+u / Ctrl+d work in copy mode
bind -T copy-mode-vi C-u send-keys -X halfpage-up
bind -T copy-mode-vi C-d send-keys -X halfpage-down

# Optional: make entering copy mode easy
bind [ copy-mode
